version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: pg_container
    environment:
      POSTGRES_DB: contabilidad_diario
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5051:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5053:80"
    depends_on:
      - postgres

volumes:
  pg_data:
